<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Asynchronous-JavaScript</title>
  </head>

  <body>

    <script>
        // !!! so actually Promise can represents a function executed in half way or finished, it's a essentially a function.
        const fetchPromise = fetch(
            "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );

        console.log(fetchPromise);

        fetchPromise.then((response) => {
            console.log(`Received response: ${response.status}`);
        });

        console.log("Started requestâ€¦");

        // Here we are:
            // 1.calling the fetch() API, and assigning the return value to the fetchPromise variable
            // 2.immediately after, logging the fetchPromise variable. This should output something like: Promise { <state>: "pending" }, telling us that we have a Promise object, and it has a state whose value is "pending". The "pending" state means that the fetch operation is still going on.
            // 3.passing a handler function into the Promise's then() method. When (and if) the fetch operation succeeds, the promise will call our handler, passing in a Response object, which contains the server's response.
            // 4.logging a message that we have started the request.


        // 2.Chaining promises

        // the elegant feature of promises is that then() itself returns a promise, which will be completed with the result of the function passed to it. This means that we can (and certainly should) rewrite the above code like this:
        const fetchPromise2 = fetch(
                "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );

        fetchPromise2
            .then((response) => response.json())
            .then((data) => {
                console.log(data[0].name);
        });
        // Instead of calling the second then() inside the handler for the first then(), we can return the promise returned by json(), and call the second then() on that return value. This is called promise chaining and means we can avoid ever-increasing levels of indentation when we need to make consecutive asynchronous function calls.

        // Before we move on to the next step, there's one more piece to add. We need to check that the server accepted and was able to handle the request, before we try to read it. We'll do this by checking the status code in the response and throwing an error if it wasn't "OK":
        const fetchPromise3 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );

        fetchPromise3
        .then((response) => {
            if (!response.ok) {
                throw new Error(`HTTP error: ${response.status}`);
            }
            return response.json();
        })
        .then((data) => {
            console.log(data[0].name);
        });


        // 3.Catching errors
        // To support error handling, Promise objects provide a catch() method. This is a lot like then(): you call it and pass in a handler function. However, while the handler passed to then() is called when the asynchronous operation succeeds, the handler passed to catch() is called when the asynchronous operation fails.

        // Try this version of our fetch() code. We've added an error handler using catch(), and also modified the URL so the request will fail.
        const fetchPromise4 = fetch(
        "bad-scheme://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );

        fetchPromise
        .then((response) => {
            if (!response.ok) {
            throw new Error(`HTTP error: ${response.status}`);
            }
            return response.json();
        })
        .then((data) => {
            console.log(data[0].name);
        })
        .catch((error) => {
            console.error(`Could not get products: ${error}`);
        });


        // 4.Combining multiple promises
        // The promise chain is what you need when your operation consists of several asynchronous functions, and you need each one to complete before starting the next one. But there are other ways you might need to combine asynchronous function calls, and the Promise API provides some helpers for them.

        // Sometimes, you need all the promises to be fulfilled, but they don't depend on each other. In a case like that, it's much more efficient to start them all off together, then be notified when they have all fulfilled. The Promise.all() method is what you need here. It takes an array of promises and returns a single promise.

        // The promise returned by Promise.all() is:
        //      1.fulfilled when and if all the promises in the array are fulfilled. In this case, the then() handler is called with an array of all the responses, in the same order that the promises were passed into all().
        //      2.rejected when and if any of the promises in the array are rejected. In this case, the catch() handler is called with the error thrown by the promise that rejected.
        // 4.1.For example:
        const fetchPromise411 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );
        const fetchPromise412 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/not-found",
        );
        const fetchPromise413 = fetch(
        "https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json",
        );

        Promise.all([fetchPromise411, fetchPromise412, fetchPromise413])
        .then((responses) => {
            for (const response of responses) {
            console.log(`${response.url}: ${response.status}`);
            }
        })
        .catch((error) => {
            console.error(`Failed to fetch: ${error}`);
        });
        // Here, we're making three fetch() requests to three different URLs. If they all succeed, we will log the response status of each one. If any of them fail, then we're logging the failure.

        // With the URLs we've provided, all the requests should be fulfilled, although for the second, the server will return 404 (Not Found) instead of 200 (OK) because the requested file does not exist. So the output should be:
        // https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json: 200
        // https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/not-found: 404
        // https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json: 200

        // 4.2.If we try the same code with a badly formed URL, like this:
        const fetchPromise421 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );
        const fetchPromise422 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/not-found",
        );
        const fetchPromise423 = fetch(
        "bad-scheme://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json",
        );

        Promise.all([fetchPromise421, fetchPromise422, fetchPromise423])
        .then((responses) => {
            for (const response of responses) {
            console.log(`${response.url}: ${response.status}`);
            }
        })
        .catch((error) => {
            console.error(`Failed to fetch: ${error}`);
        });
        // Then we can expect the catch() handler to run, and we should see something like:
        // Failed to fetch: TypeError: Failed to fetch(the then() function is not invoked, and the catch() function is invoked.)

        // 4.3.Sometimes, you might need any one of a set of promises to be fulfilled, and don't care which one. In that case, you want Promise.any(). This is like Promise.all(), except that it is fulfilled as soon as any of the array of promises is fulfilled, or rejected if all of them are rejected:
        const fetchPromise431 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        );
        const fetchPromise432 = fetch(
        "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/not-found",
        );
        const fetchPromise433 = fetch(
        "https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json",
        );

        Promise.any([fetchPromise1, fetchPromise2, fetchPromise3])
        .then((response) => {
            console.log(`${response.url}: ${response.status}`);
        })
        .catch((error) => {
            console.error(`Failed to fetch: ${error}`);
        });


        // 5.async and await
        // The async keyword gives you a simpler way to work with asynchronous promise-based code. Adding async at the start of a function makes it an async function:
        async function myFunction() {
        // This is an async function
        }

        // Inside an async function, you can use the await keyword before a call to a function that returns a promise. This makes the code wait at that point until the promise is settled, at which point the fulfilled value of the promise is treated as a return value, or the rejected value is thrown.

        // This enables you to write code that uses asynchronous functions but looks like synchronous code. For example, we could use it to rewrite our fetch example:
        async function fetchProducts() {
            try {
                // after this line, our function will wait for the `fetch()` call to be settled
                // the `fetch()` call will either return a Response or throw an error
                const response = await fetch(
                    "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
                );
                if (!response.ok) {
                    throw new Error(`HTTP error: ${response.status}`);
                }
                // after this line, our function will wait for the `response.json()` call to be settled
                // the `response.json()` call will either return the parsed JSON object or throw an error
                const data = await response.json();
                console.log(data[0].name);
            } catch (error) {
                console.error(`Could not get products: ${error}`);
            }
        }

        fetchProducts();
        // Here, we are calling await fetch(), and instead of getting a Promise, our caller gets back a fully complete Response object, just as if fetch() were a synchronous function!
        
        // We can even use a try...catch block for error handling, exactly as we would if the code were synchronous. 


        // 6.differentiate "Promise" object and "Response" object
        // 6.1.Note though that async functions always return a promise, so you can't do something like:

        // async function fetchProducts() {
        //   try {
        //     const response = await fetch(
        //       "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        //     );
        //     if (!response.ok) {
        //       throw new Error(`HTTP error: ${response.status}`);
        //     }
        //     const data = await response.json();
        //     return data;
        //   } catch (error) {
        //     console.error(`Could not get products: ${error}`);
        //   }
        // }

        // const promise = fetchProducts();
        // console.log(promise[0].name); // "promise" is a Promise object, so this will not work


        // 6.2.Instead, you'd need to do something like:

        // async function fetchProducts() {
        //   try {
        //     const response = await fetch(
        //       "https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json",
        //     );
        //     if (!response.ok) {
        //       throw new Error(`HTTP error: ${response.status}`);
        //     }
        //     const data = await response.json();
        //     return data;
        //   } catch (error) {
        //     console.error(`Could not get products: ${error}`);
        //   }
        // }

        // const promise = fetchProducts();
        // promise.then((data) => console.log(data[0].name));


    </script>
  </body>

</html>